### ISSUE TITLE
报警规则支持配置机器类型

### ISSUE THREAD

**Issue by lostyear** [didi/nightingale#441]
期望能够在报警规则里支持配置，一个报警规则是在物理机生效还是虚拟机生效

当前报警规则是比较统一的，但是在复杂情况下，如果同时存在物理机、虚拟机、容器等多种实例的情况，部分报警可能需要区分配置。
可以直接利用设备信息中的设备分类来实现区分

**Comment by UlricQin** [comment]
当前阶段，建议不同类别的资源拆节点挂载~短期不考虑支持按照资源类别报警哈 Ulric Qin 邮箱：ulric.qin@gmail.com 签名由 网易邮箱大师 定制 在2020年12月05日 12:22，Paul Chu 写道： 期望能够在报警规则里支持配置，一个报警规则是在物理机生效还是虚拟机生效 当前报警规则是比较统一的，但是在复杂情况下，如果同时存在物理机、虚拟机、容器等多种实例的情况，部分报警可能需要区分配置。 可以直接利用设备信息中的设备分类来实现区分 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by UlricQin** [comment]
清理历史遗留issue，如有问题，请reopen
